### ISSUE TITLE
fadeTo creates extra colors. I would prefer it didn't.

### ISSUE THREAD

**Issue by NickBentley** [jbobrow/Move38-blinks-firmware#17]
When I use fadeTo to transition between 2 colors (for example, red and green), it transitions through the color between them (this case yellow). For visual simplicity, ideally, there should be no third color in the transition. I think it's important for real time games where the colors are transitioning quickly.

**Comment by jbobrow** [comment]
`fadeTo()` now fades directly to the color it is headed towards... linear RGB path. Rainbow effects are accomplished with `fadeToRainbow()`
