### ISSUE TITLE
Button press ISP correct?

### ISSUE THREAD

**Issue by bigjosh** [jbobrow/Move38-blinks-firmware#2]
The button pin is active HIGH, so is this correct? Or maybe just works anyway because wake eventually gets set right elsewhere? If so, we can delete this function completely and save all those PUSHes and POPs.

```
//INT0 interrupt triggered when the pushbutton is pressed
ISR(PCINT1_vect){
	if((DDRB & BUTTON)==0)          // TODO: This looks wrong? Button is active high
		wake = 1;
}
```

**Comment by jbobrow** [comment]
Hmmm. When the pushbutton is pressed, all IR LEDs are lit, so that would suggest HIGH when active. Are you finding that the pushbutton isn't working? Not sure I understand where the pushing and popping is happening here, is that in this code?

**Comment by bigjosh** [comment]
Pretty sure active high. Schematic here:

![image](https://cloud.githubusercontent.com/assets/5520281/21871742/29fa294c-d832-11e6-922e-fb26947b2a31.png)

If it hasn't bitten you yet, then let's eave it be.
