### ISSUE TITLE
Sneeky printf()

### ISSUE THREAD

**Issue by bigjosh** [jbobrow/Move38-blinks-firmware#7]
Looks like a printf sneeked in....

[https://github.com/jbobrow/Move38-blinks-firmware/blob/master/avr/cores/AutomaTile/AutomaTile.c#L255
](https://github.com/jbobrow/Move38-blinks-firmware/blob/master/avr/cores/AutomaTile/AutomaTile.c#L255
)

That pulls in about 2K and causes other problems.  

For now, take it out and you should get back a lot of space.  We can talk later about systematic defenses against this.

**Comment by LasVegasOle** [comment]
awesome! thanks for catching it.
